steps:

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t',
           'gcr.io/tw-rd-sp-tim/ci-flask:4.0',
           '.']

  # Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push',
           'gcr.io/tw-rd-sp-tim/ci-flask:4.0']

    env:
      - 'CLOUDSDK_COMPUTE_REGION=us-central1'
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'