steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - run
      - deploy
      - ci-flask-functions
      - --region=asia-east1
      - --image=gcr.io/tw-rd-sp-tim/ci-flask-prod:1.0
      - --platform=managed