steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - functions
      - deploy
      - ci-flask-functions
      - --region=asia-east1
      - --source=.
      - --trigger-http
      - --runtime=python38