# Tim Chiang

steps:
  # [START CI]
  - name: 'python'
    id: TestCase
    entrypoint: python
    args: ['-c', 'pip install flask && python test_app.py -v']

  - name: 'gcr.io/cloud-builders/docker'
    id: Build
    args: ['build', '-t',
           'gcr.io/tw-rd-sp-tim/ci-flask-prod:${SHORT_SHA}',
           '.']

  - name: 'gcr.io/cloud-builders/docker'
    id: Push
    args: ['push',
           'gcr.io/tw-rd-sp-tim/ci-flask-prod:${SHORT_SHA}']
  # [END CI]

  # [START CD]
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
        - gcloud
        - run
        - deploy
        - ci-flask-functions-${SHORT_SHA}
        - --allow-unauthenticated
        - --region=asia-east1
        - --image=gcr.io/tw-rd-sp-tim/ci-flask-prod:2.0
        - --platform=managed