steps:
  # [START CI]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t',
           'gcr.io/tw-rd-sp-tim/ci-flask-prod:2.0',
           '.']

  # Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push',
           'gcr.io/tw-rd-sp-tim/ci-flask-prod:2.0']

  # [START CD]
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
        - gcloud
        - run
        - deploy
        - ci-flask-functions
        - --allow-unauthenticated
        - --region=asia-east1
        - --image=gcr.io/tw-rd-sp-tim/ci-flask-prod:2.0
        - --platform=managed